packages:
  # 前端管理端
  - 'admin'
  # 实体类及工具函数
  - 'common'
  # 配置
  - 'config'
  # 大屏
  - 'dashboard'
  # 子项目
  - 'packages/*'
  # prisma 生成的文件
  - 'prisma-generated'
  # 后端
  - 'server'
  # test
  - 'test'
