import * as Cesium from 'cesium'
import { DropdownDividerOption, DropdownGroupOption, DropdownOption, DropdownRenderOption } from "naive-ui";

export enum EDIT_TYPE_ENUM {
  DEFAULT = 'default',
  INS_SIGNAL_LIGHT_GROUP = 'INS_SIGNAL_LIGHT_GROUP',
  UPD_SIGNAL_LIGHT_GROUP = 'UPD_SIGNAL_LIGHT_GROUP',
  INS_SIGNAL_LIGHT = 'INS_SIGNAL_LIGHT',
  UPD_SIGNAL_LIGHT = 'UPD_SIGNAL_LIGHT',
  INS_FLIGHT_RESTRICTION_ZONE = 'INS_FLIGHT_RESTRICTION_ZONE',
  UPD_FLIGHT_RESTRICTION_ZONE = 'UPD_FLIGHT_RESTRICTION_ZONE',
  INS_FLIGHT_ROUTE = 'INS_FLIGHT_ROUTE',
  UPD_FLIGHT_ROUTE = 'UPD_FLIGHT_ROUTE',
  INS_APPLY_AIRSPACE = 'INS_APPLY_AIRSPACE',
  INS_APPLY_FLIGHT_ROUTE = 'INS_APPLY_FLIGHT_ROUTE',
}

export const EDIT_TYPE_DICT = {
  [EDIT_TYPE_ENUM.DEFAULT]: '',
  [EDIT_TYPE_ENUM.INS_SIGNAL_LIGHT_GROUP]: '新增信号灯组',
  [EDIT_TYPE_ENUM.UPD_SIGNAL_LIGHT_GROUP]: '修改信号灯组',
  [EDIT_TYPE_ENUM.INS_SIGNAL_LIGHT]: '新增子信号灯',
  [EDIT_TYPE_ENUM.UPD_SIGNAL_LIGHT]: '修改子信号灯',
  [EDIT_TYPE_ENUM.INS_FLIGHT_RESTRICTION_ZONE]: '新增限飞区',
  [EDIT_TYPE_ENUM.UPD_FLIGHT_RESTRICTION_ZONE]: '修改限飞区',
  [EDIT_TYPE_ENUM.INS_FLIGHT_ROUTE]: '新增航线',
  [EDIT_TYPE_ENUM.UPD_FLIGHT_ROUTE]: '修改航线',
  [EDIT_TYPE_ENUM.INS_APPLY_AIRSPACE]: '用户申请空域',
  [EDIT_TYPE_ENUM.INS_APPLY_FLIGHT_ROUTE]: '用户申请航线',
}
// 需要连续绘制
export const EDIT_TYPES_SPECIAL_1 = [
  EDIT_TYPE_ENUM.INS_FLIGHT_RESTRICTION_ZONE,
  EDIT_TYPE_ENUM.UPD_FLIGHT_RESTRICTION_ZONE,
  EDIT_TYPE_ENUM.INS_FLIGHT_ROUTE,
  EDIT_TYPE_ENUM.UPD_FLIGHT_ROUTE,
  EDIT_TYPE_ENUM.INS_APPLY_AIRSPACE,
  EDIT_TYPE_ENUM.INS_APPLY_FLIGHT_ROUTE,
]
// 连续绘制时展示多边形
export const EDIT_TYPES_SPECIAL_1_GEOMETRY = [
  EDIT_TYPE_ENUM.INS_FLIGHT_RESTRICTION_ZONE,
  EDIT_TYPE_ENUM.UPD_FLIGHT_RESTRICTION_ZONE,
  EDIT_TYPE_ENUM.INS_APPLY_AIRSPACE,
]
// 连续绘制时展示路径
export const EDIT_TYPES_SPECIAL_1_POLYLINE = [
  EDIT_TYPE_ENUM.INS_FLIGHT_ROUTE,
  EDIT_TYPE_ENUM.UPD_FLIGHT_ROUTE,
  EDIT_TYPE_ENUM.INS_APPLY_FLIGHT_ROUTE,
]

export const ID_PREFIX_POINT = 'ID_PREFIX_POINT::::::::::'
export const ID_PREFIX_LINE = 'ID_PREFIX_LINE::::::::::'

const ID_PREFIX_SPECIAL = 'ID_PREFIX_SPECIAL::::::::::'
export const ID_SPECIAL_MouseMovingPoint = `${ID_PREFIX_SPECIAL}MouseMovingPoint`
export const ID_SPECIAL_MouseMovingGeometry = `${ID_PREFIX_SPECIAL}MouseMovingGeometry`
export const ID_SPECIAL_MouseMovingPolyline = `${ID_PREFIX_SPECIAL}MouseMovingPolyline`
export const ID_SPECIAL_preview_MouseMovingGeometry = `${ID_PREFIX_SPECIAL}preview_MouseMovingGeometry`
export const ID_SPECIAL_preview_MouseMovingPolyline = `${ID_PREFIX_SPECIAL}preview_MouseMovingPolyline`

// 信号灯组
export const ID_PREFIX_SIGNAL_LIGHT_GROUP = 'ID_PREFIX_SIGNAL_LIGHT_GROUP::::::::::'
// 子信号灯
export const ID_PREFIX_SIGNAL_LIGHT = 'ID_PREFIX_SIGNAL_LIGHT::::::::::'

// 车辆
export const ID_PREFIX_VEHICLE_REAL_TIME = 'ID_PREFIX_VEHICLE_REAL_TIME::::::::::'
// 航空器
export const ID_PREFIX_AIRCRAFT_REAL_TIME = 'ID_PREFIX_AIRCRAFT_REAL_TIME::::::::::'

// 限飞区
export const ID_PREFIX_FLIGHT_RESTRICTION_ZONE = 'ID_PREFIX_FLIGHT_RESTRICTION_ZONE::::::::::'
// 航线
export const ID_PREFIX_FLIGHT_ROUTE = 'ID_PREFIX_FLIGHT_ROUTE::::::::::'
// 用户申请空域
export const ID_PREFIX_FLIGHT_AIRSPACE_USER_APPLY = 'ID_PREFIX_FLIGHT_AIRSPACE_USER_APPLY::::::::::'
// 用户申请航线
export const ID_PREFIX_FLIGHT_ROUTE_USER_APPLY = 'ID_PREFIX_FLIGHT_ROUTE_USER_APPLY::::::::::'

// ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== 默认值 ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
export const CESIUM_DEFAULT = {
  // 点高度
  HEIGHT_POINT: 0,
  // 点颜色
  COLOR_POINT: Cesium.Color.WHITE,

  // 线高度
  HEIGHT_LINE: 0,
  // 线颜色
  COLOR_LINE: Cesium.Color.WHITE,

  // 信号灯组高度
  HEIGHT_SIGNAL_LIGHT_GROUP: 0,
  // 信号灯组图片宽度
  SIGNAL_LIGHT_GROUP_PIC_WIDTH: 32,
  // 信号灯组图片高度
  SIGNAL_LIGHT_GROUP_PIC_HEIGHT: 32,

  // 子信号灯高度
  HEIGHT_SIGNAL_LIGHT: 0.01,
  // 子信号灯图片宽度
  SIGNAL_LIGHT_PIC_WIDTH: 24,
  // 子信号灯图片高度
  SIGNAL_LIGHT_PIC_HEIGHT: 24,

  // 车辆高度
  HEIGHT_VEHICLE: 0.1,
  // 车辆轨迹颜色
  COLOR_VEHICLE_TRAJECTORY: Cesium.Color.GREEN,
  // 车辆轨迹标识高度
  HEIGHT_VEHICLE_TRAJECTORY_MARK: 0.1,

  // 限飞区高度
  HEIGHT_FLIGHT_RESTRICTION_ZONE: 0.02,
  // 限飞区默认颜色
  COLOR_DEFAULT_FLIGHT_RESTRICTION_ZONE: Cesium.Color.BLUE.withAlpha(0.5),
  COLOR_OUTLINE_DEFAULT_FLIGHT_RESTRICTION_ZONE: Cesium.Color.BLUE.withAlpha(0.5),
  WIDTH_OUTLINE_DEFAULT_FLIGHT_RESTRICTION_ZONE: 10,
  // 禁飞区
  COLOR_JFQ_FLIGHT_RESTRICTION_ZONE: Cesium.Color.RED.withAlpha(0.5),
  COLOR_OUTLINE_JFQ_FLIGHT_RESTRICTION_ZONE: Cesium.Color.RED.withAlpha(0.5),
  // 限高区
  COLOR_XGQ_FLIGHT_RESTRICTION_ZONE: Cesium.Color.GREY.withAlpha(0.5),
  COLOR_OUTLINE_XGQ_FLIGHT_RESTRICTION_ZONE: Cesium.Color.GREY.withAlpha(0.5),

  // 航线颜色
  COLOR_DEFAULT_FLIGHT_ROUTE: Cesium.Color.BLUE.withAlpha(0.5),
  // 默认航线高度
  HEIGHT_DEFAULT_FLIGHT_ROUTE: 100,
}

export type ContextMenuOptionType = Array<DropdownOption | DropdownGroupOption | DropdownDividerOption | DropdownRenderOption>;
